resources:
  - name: goservice_gitRepo_demo
    type: GitRepo
    configuration:
      path: eladh/pipeline-webinar-demo
      gitProvider: git

  - name: svc_build_info_demo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: svc_build
      buildNumber: 1

  - name: svc_promoted_build_info_demo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: svc_build
      buildNumber: 1

  - name: backend_gitRepo_demo
    type: GitRepo
    configuration:
      path: eladh/pipeline-webinar-demo
      gitProvider: git

  - name: app_build_info_demo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: backend_build
      buildNumber: 1

  - name: app_promoted_build_info_demo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: backend_build
      buildNumber: 1

  - name: frontend_gitRepo_demo
    type: GitRepo
    configuration:
      path: eladh/pipeline-webinar-demo
      gitProvider: git

  - name: releaseBundle_demo
    type: ReleaseBundle
    configuration:
      sourceDistribution: dist
      name: demo-app
      version: v2.0.0

  - name: signedBundle_demo
    type: ReleaseBundle
    configuration:
      sourceDistribution: dist
      name: demo-app
      version: v2.0.0

  - name: distributionRules_demo
    type: DistributionRule
    configuration:
      sourceDistribution: dist
      serviceName: "*"
      siteName: "*"
      cityName: "Bengaluru"
      countryCodes:
        - "*"

pipelines:
  - name: service
    steps:
      - name: bld_svc_demo
        type: DockerBuild
        configuration:
          dockerFileLocation: demo/swampup-go-service
          dockerFileName: Dockerfile
          dockerImageName: docker.artifactory.bookdemos.bookdemos/docker-local/gosvc
          dockerImageTag: $run_number
          inputResources:
            - name: goservice_gitRepo_demo
          integrations:
            - name: art

      - name: push_svc_demo
        type: DockerPush
        configuration:
          targetRepository: docker-local
          integrations:
            - name: art
          inputSteps:
            - name: bld_svc_demo

      - name: publish_svc_build_demo
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: push_svc_demo
          outputResources:
            - name: svc_build_info_demo

      - name: promote_svc_build_demo
        type: PromoteBuild
        configuration:
          targetRepository: docker-prod
          integrations:
            - name: art
          inputResources:
            - name: svc_build_info_demo
          outputResources:
            - name: svc_promoted_build_info_demo

  - name: app
    steps:
      - name: bld_backend_demo
        type: MvnBuild
        configuration:
          sourceLocation: ./demo/swampup-java-backend-service
          mvnCommand: clean install -ntp
          configFileLocation: .
          configFileName: mvn-art-config
          inputResources:
            - name: backend_gitRepo_demo
          integrations:
            - name: art
        execution:
          onStart:
            - apt-get update
            - apt install default-jdk
            - pushd /tmp
            - wget http://mirrors.estointernet.in/apache/maven/maven-3/3.6.1/binaries/apache-maven-3.6.1-bin.tar.gz
            - tar xzvf apache-maven-3.6.1-bin.tar.gz
            - export PATH=$PATH:/tmp/apache-maven-3.6.1/bin
            - export M2_HOME=/tmp/apache-maven-3.6.1/
            - popd
            - javac -version
            - mvn --version
      - name: bld_frontend
        type: NpmBuild
        configuration:
          sourceLocation: demo/swampup-vue-frontend
          repositoryName: npm
          inputResources:
            - name: frontend_gitRepo_demo
          integrations:
            - name: art

      - name: pack_frontend
        type: Bash
        configuration:
          inputSteps:
            - name: bld_frontend
          integrations:
            - name: art
        execution:
          onStart:
            - export tempStateLocation="$step_tmp_dir/npmSourceState"
            - restore_run_files npmBuildInputGitRepo $tempStateLocation
            - pushd $tempStateLocation
            - cd demo/swampup-vue-frontend
            - npm run build
            - add_run_files $tempStateLocation/. npmBuildInputGitRepo

      - name: publish_frontend_demo
        type: NpmPublish
        configuration:
          repositoryName: npm-local
          inputSteps:
            - name: pack_frontend
          integrations:
            - name: art
        execution:
          onStart:
            - export inputNpmBuildStepName="bld_frontend"

      - name: build_app_demo
        type: Bash
        configuration:
          environmentVariables:
            dockerImageName: docker.artifactory.bookdemos.bookdemos/docker-local/app
            dockerImageTag: ${run_number}
          inputResources:
            - name: backend_gitRepo_demo
          inputSteps:
            - name: bld_backend_demo
            - name: publish_frontend_demo
          integrations:
            - name: art
        execution:
          onStart:
            - rm -rf $run_dir/workspace/jfrog
            - retry_command jfrog rt config --url $int_art_url --user $int_art_user --apikey $int_art_apikey --interactive=false
            - pushd $res_backend_gitRepo_demo_resourcePath
            - echo $int_art_url
            - echo $run_Number
            - cd demo/swampup-java-backend-service
            - add_run_variables buildStepName=${step_name}
            - add_run_variables ${step_name}_buildNumber=${run_number}
            - add_run_variables ${step_name}_buildName=${pipeline_name}
            - docker build --pull --no-cache -t $dockerImageName:$dockerImageTag --build-arg REGISTRY=${int_art_url} .
            - jfrog rt bce $pipeline_name $run_number
            - jfrog rt docker-push $dockerImageName:$dockerImageTag docker-local --build-name=$pipeline_name --build-number=$run_number
            - add_run_files /tmp/jfrog/. jfrog

      - name: publish_app_build_demo
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: build_app_demo
          outputResources:
            - name: app_build_info_demo

      - name: promote_app_build
        type: PromoteBuild
        configuration:
          targetRepository: demo
          integrations:
            - name: art
          inputResources:
            - name: app_build_info_demo
          outputResources:
            - name: app_promoted_build_info_demo