resources:
  - name: goservice_gitRepo_demo
    type: GitRepo
    configuration:
      path: eladh/pipeline-webinar-demo
      gitProvider: git

  - name: svc_build_info_demo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: svc_build
      buildNumber: 1

  - name: svc_promoted_build_info_demo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: svc_build
      buildNumber: 1


  - name: releaseBundle_demo
    type: ReleaseBundle
    configuration:
      sourceDistribution: dist
      name: demo-app
      version: v2.0.0

  - name: signedBundle_demo
    type: ReleaseBundle
    configuration:
      sourceDistribution: dist
      name: demo-app
      version: v2.0.0

  - name: distributionRules_demo
    type: DistributionRule
    configuration:
      sourceDistribution: dist
      serviceName: "*"
      siteName: "*"
      cityName: "*"
      countryCodes:
        - "*"

  - name: deploy_vm_demo
    type: VmCluster
    configuration:
      sshKey: deploy_ssh
      targets:
        - 35.224.230.233

pipelines:
  - name: service
    steps:
      - name: bld_svc_demo
        type: DockerBuild
        configuration:
          dockerFileLocation: demo/swampup-go-service
          dockerFileName: Dockerfile
          dockerImageName: docker.artifactory.bookdemos.bookdemos/docker-local/gosvc
          dockerImageTag: $run_number
          inputResources:
            - name: goservice_gitRepo_demo
          integrations:
            - name: art

      - name: push_svc_demo
        type: DockerPush
        configuration:
          targetRepository: docker-local
          integrations:
            - name: art
          inputSteps:
            - name: bld_svc_demo

      - name: publish_svc_build_demo
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: push_svc_demo
          outputResources:
            - name: svc_build_info_demo

      - name: promote_svc_build_demo
        type: PromoteBuild
        configuration:
          targetRepository: docker-prod
          integrations:
            - name: art
          inputResources:
            - name: svc_build_info_demo
          outputResources:
            - name: svc_promoted_build_info_demo

  - name: release
    steps:
      - name: bundle
        type: CreateReleaseBundle
        configuration:
          releaseBundleName: demo-app
          releaseBundleVersion: v2.0.$run_number
          dryRun: false
          sign: false
          description: "some random test description"
          inputResources:
            - name: svc_promoted_build_info_demo
              trigger: false
          outputResources:
            - name: releaseBundle_demo

      - name: sign_demo
        type: SignReleaseBundle
        configuration:
          inputResources:
            - name: releaseBundle_demo
          outputResources:
            - name: signedBundle_demo

      - name: distribute
        type: DistributeReleaseBundle
        configuration:
          dryRun: false
          inputResources:
            - name: signedBundle_demo
            - name: distributionRules_demo
          integrations:
            - name: dist

      - name: deploy
        type: Bash
        configuration:
          environmentVariables:
            docker_repository: docker-prod
            artifactory_address: docker.artifactory.bookdemos.bookdemos
          integrations:
            - name: edge_art
          inputResources:
            - name: deploy_vm_demo
            - name: svc_promoted_build_info_demo
              trigger: false
          inputSteps:
            - name: distribute
        execution:
          onExecute:
            - ssh -i ~/.ssh/deploy_vm_demo eladh@${res_deploy_vm_demo_targets_0} sudo /home/eladh/deploy-to-prod.sh $artifactory_address $docker_repository $int_edge_art_apikey $res_svc_promoted_build_info_demo_buildNumber