resources:
  - name: goservice_gitRepo_demo
    type: GitRepo
    configuration:
      path: eladh/pipeline-webinar-demo
      gitProvider: git

  - name: svc_build_info_demo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: svc_build
      buildNumber: 1

  - name: svc_promoted_build_info_demo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: svc_build
      buildNumber: 1

  - name: backend_gitRepo_demo
    type: GitRepo
    configuration:
      path: eladh/pipeline-webinar-demo
      gitProvider: git

  - name: app_build_info_demo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: backend_build
      buildNumber: 1

  - name: app_promoted_build_info_demo
    type: BuildInfo
    configuration:
      sourceArtifactory: art
      buildName: backend_build
      buildNumber: 1

  - name: frontend_gitRepo_demo
    type: GitRepo
    configuration:
      path: eladh/pipeline-webinar-demo
      gitProvider: git

  - name: releaseBundle_demo
    type: ReleaseBundle
    configuration:
      sourceDistribution: dist
      name: demo-app
      version: v2.0.0

  - name: signedBundle_demo
    type: ReleaseBundle
    configuration:
      sourceDistribution: dist
      name: demo-app
      version: v2.0.0

  - name: distributionRules_demo
    type: DistributionRule
    configuration:
      sourceDistribution: dist
      serviceName: "*"
      siteName: "*"
      cityName: "*"
      countryCodes:
        - "*"

  - name: deploy_vm_demo
    type: VmCluster
    configuration:
      sshKey: deploy_ssh
      targets:
        - 35.224.230.233

pipelines:


  - name: app
    steps:
      - name: bld_backend_demo
        type: MvnBuild
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: drydock/u18java
                tag: master
          sourceLocation: demo/swampup-java-backend-service
          mvnCommand: clean install -ntp
          configFileLocation: .
          configFileName: mvn-art-config
          inputResources:
            - name: backend_gitRepo_demo
          integrations:
            - name: art

      - name: bld_frontend
        type: Bash
        configuration:
          runtime:
            type: image
            image:
              custom:
                name: drydock/u16nodall
                tag: v7.2.4
          inputResources:
            - name: frontend_gitRepo_demo
          integrations:
            - name: art
        execution:
          onStart:
            - cd $res_src_resourcePath
            - ls -lh
            - cd demo/swampup-vue-frontend
            - npm install


      - name: pack_frontend
        type: Bash
        configuration:
          inputSteps:
            - name: bld_frontend
          integrations:
            - name: art
        execution:
          onStart:
            - export tempStateLocation="$step_tmp_dir/npmSourceState"
            - restore_run_files npmBuildInputGitRepo $tempStateLocation
            - pushd $tempStateLocation
            - cd demo/swampup-vue-frontend
            - npm run build
            - add_run_files $tempStateLocation/. npmBuildInputGitRepo

      - name: publish_frontend_demo
        type: NpmPublish
        configuration:
          repositoryName: npm-local
          inputSteps:
            - name: pack_frontend
          integrations:
            - name: art
        execution:
          onStart:
            - export inputNpmBuildStepName="bld_frontend"

      - name: build_app_demo
        type: Bash
        configuration:
          environmentVariables:
            dockerImageName: artifactory-swampup.jfrogdev.co/docker-local/app
            dockerImageTag: ${run_number}
          inputResources:
            - name: backend_gitRepo_demo
          inputSteps:
            - name: bld_backend_demo
            - name: publish_frontend_demo
          integrations:
            - name: art
        execution:
          onStart:
            - rm -rf $run_dir/workspace/jfrog
            - retry_command jfrog rt config --url $int_art_url --user $int_art_user --apikey $int_art_apikey --interactive=false
            - pushd $res_backend_gitRepo_demo_resourcePath
            - echo $int_art_url
            - echo $run_Number
            - cd demo/swampup-java-backend-service
            - add_run_variables buildStepName=${step_name}
            - add_run_variables ${step_name}_buildNumber=${run_number}
            - add_run_variables ${step_name}_buildName=${pipeline_name}
            - docker build --pull --no-cache -t $dockerImageName:$dockerImageTag --build-arg REGISTRY=${int_art_url} .
            - jfrog rt bce $pipeline_name $run_number
            - jfrog rt docker-push $dockerImageName:$dockerImageTag docker-local --build-name=$pipeline_name --build-number=$run_number
            - save_run_state /tmp/jfrog/. jfrog

      - name: publish_app_build_demo
        type: PublishBuildInfo
        configuration:
          inputSteps:
            - name: build_app_demo
          outputResources:
            - name: app_build_info_demo

      - name: promote_app_build
        type: PromoteBuild
        configuration:
          targetRepository: npm-local
          inputResources:
            - name: app_build_info_demo
          outputResources:
            - name: app_promoted_build_info_demo

  - name: release
    steps:
      - name: bundle
        type: CreateReleaseBundle
        configuration:
          releaseBundleName: demo-app
          releaseBundleVersion: v2.0.$run_number
          dryRun: false
          sign: false
          description: "some random test description"
          inputResources:
            - name: svc_promoted_build_info_demo
              trigger: false
          outputResources:
            - name: releaseBundle_demo

      - name: sign_demo
        type: SignReleaseBundle
        configuration:
          inputResources:
            - name: releaseBundle_demo
          outputResources:
            - name: signedBundle_demo

      - name: distribute
        type: DistributeReleaseBundle
        configuration:
          dryRun: false
          inputResources:
            - name: signedBundle_demo
            - name: distributionRules_demo
          integrations:
            - name: dist

      - name: deploy
        type: Bash
        configuration:
          environmentVariables:
            artifactory_address: docker.artifactory.bookdemos.bookdemos
          integrations:
            - name: art
          inputResources:
            - name: deploy_vm_demo
            - name: svc_promoted_build_info_demo
              trigger: false
          inputSteps:
            - name: distribute
        execution:
          onExecute:
            - ssh -i ~/.ssh/deploy_vm_demo eladh@${res_deploy_vm_demo_targets_0} sudo /home/eladh/deploy-to-prod.sh $artifactory_address $int_art_apikey $res_svc_promoted_build_info_demo_buildNumber